### ISSUE TITLE
when release code?

### ISSUE THREAD

**Issue by buwangchuxin1992** [xdFai/ASCNet#1]
Thanks for your excellent work.I wonder when to release the code(train and test code)?Thanks

**Comment by xdFai** [comment]
Unfortunately, the paper was just rejected. I plan to release the code once it gets accepted.




xdApp
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xdFai/ASCNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月15日(星期四) 下午4:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xdFai/ASCNet] when release code? (Issue #1)





 
Thanks for your excellent work.I wonder when to release the code(train and test code)?Thanks
